import { colors } from "./colors";

export const semanticColors = {
  marketing: {
    canvas: colors.sand[50],
    canvasAlt: colors.sand[100],
    surface: "rgba(255, 255, 255, 0.82)",
    surfaceStrong: colors.ink[950],
    text: colors.ink[950],
    textMuted: colors.mineral[600],
    heading: colors.ink[900],
    border: "rgba(24, 48, 54, 0.12)",
    borderStrong: "rgba(24, 48, 54, 0.22)",
    accentPrimary: colors.copper[500],
    accentSecondary: colors.sage[600],
    accentSoft: colors.sage[100],
    grid: "rgba(24, 48, 54, 0.06)",
  },
  platform: {
    canvas: colors.mineral[50],
    canvasAlt: colors.sand[50],
    surface: "#ffffff",
    surfaceMuted: colors.mineral[100],
    surfaceStrong: colors.ink[900],
    text: colors.ink[950],
    textMuted: colors.mineral[700],
    heading: colors.ink[900],
    border: "rgba(36, 51, 61, 0.1)",
    borderStrong: "rgba(36, 51, 61, 0.18)",
    accentPrimary: colors.copper[500],
    accentSecondary: colors.sage[600],
    accentSoft: colors.sage[50],
    success: colors.signal.success,
    warning: colors.signal.warning,
    danger: colors.signal.danger,
    info: colors.signal.info,
  },
  charts: {
    seriesA: colors.copper[500],
    seriesB: colors.sage[600],
    seriesC: colors.ink[500],
    seriesD: colors.mineral[500],
    grid: "rgba(36, 51, 61, 0.12)",
    axis: colors.mineral[600],
    annotation: colors.ink[900],
  },
} as const;
