export const componentCategories = {
  primitives: [
    "Button",
    "Input",
    "Textarea",
    "Select",
    "Checkbox",
    "Radio",
    "Badge",
    "Tabs",
    "Dialog",
    "Tooltip",
    "Skeleton",
  ],
  surfaces: ["Panel", "Card", "SectionShell", "MetricSurface", "InsetSurface"],
  feedback: ["InlineError", "StatusCallout", "EmptyState", "LoadingPanel", "ToastViewport"],
  dataDisplay: [
    "KeyValueList",
    "MetricCard",
    "StatusBadge",
    "Timeline",
    "TableShell",
    "ResultCard",
    "ArtifactListRow",
  ],
  layout: ["AppShell", "PageHeader", "SectionHeader", "ContentContainer"],
  navigation: ["TopNav", "SidebarNav", "Breadcrumbs"],
} as const;

export const mvpComponentOrder = [
  "Button",
  "Input",
  "Textarea",
  "Select",
  "Panel",
  "Card",
  "PageHeader",
  "StatusBadge",
  "LoadingPanel",
  "InlineError",
  "EmptyState",
  "MetricCard",
  "KeyValueList",
  "TableShell",
  "ResultCard",
  "Timeline",
] as const;
